# Generated by Django 3.1.4 on 2021-01-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
